# config\packages\nelmio_api_doc.yaml

nelmio_api_doc:
    documentation:
        info:
            title: BileMo
            description: Une API pour toute une sélection de téléphones mobiles haut de gamme !
            version: 1.0.0
        paths:
            /api/login_check:
                post:
                    tags:
                        - Login
                    summary: Se connecter à l'api.
                    requestBody:
                        content:
                            application/json:
                                schema:
                                    properties:
                                        username:
                                            type: string
                                            default: admin@bilemo.com
                                        password:
                                            type: string
                                            default: password
                                    type: object
                    responses:
                        '200':
                            description: OK
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            token:
                                                type: string
                                            refresh_token:
                                                type: string
        components:
            schemas:
                Token:
                    type: object
                    properties:
                        token:
                            type: string
                            readOnly: true
                Credentials:
                    type: object
                    properties:
                        username:
                            type: string
                            default: admin@bilemo.com
                        password:
                            type: string
                            default: password
            securitySchemes:
                bearerAuth:
                    type: apiKey
                    in: header
                    name: Authorization # or another header name
        security:
            - bearerAuth: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc